// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // El CLI (migrate, db push, studio) usa la conexión directa a Supabase,
    // no la pooled (PgBouncer no soporta bien comandos de migración).
    url: process.env["DIRECT_URL"],
  },
});
